### ISSUE TITLE
Pure python 3Di implementation

### ISSUE THREAD

**Issue by milot-mirdita** [westlake-repl/ProTrek#2]
[mini3Di](https://github.com/althonos/mini3di/tree/main/mini3di) is a pure python 3Di implementation (GPL). That would avoid the awkward Google drive distribution of Foldseek binaries. mini3Di was made by a community member and not by us.

Alternatively, you can download Foldseek binaries from either the [latest commit](https://mmseqs.com/foldseek/) or from previous commits through:
mmseqs.com/archive/COMMIT_HASH (e.g. https://mmseqs.com/archive/fc40ba1afdcb20602116907fdc73a47fd4c78615/).

**Comment by LTEnjoy** [comment]
Hi, thank you for the recommendations!

To ensure users could run our examples without unexpected errors we provide a fixed version of Foldseek binary file. Users can also manually install Foldseek on their own and run the examples.
