### ISSUE TITLE
Will the protein text data be available?

### ISSUE THREAD

**Issue by yxliu-TAMU** [westlake-repl/ProTrek#4]
Hi, thanks so much for sharing such a good repo. Just wondering are you planning to share the protein-text paired data?

**Comment by LTEnjoy** [comment]
Hi, thank you for your interest in our work!

We have not yet submitted our paper now. We will evaluate it after our paper being accepted :)

**Comment by yxliu-TAMU** [comment]
Thanks for your fast reply! Hope your article will be accepted soon.
