### ISSUE TITLE
Hello, I am a novice in biology. Can I use ProTrek for protein sequence alignment?

### ISSUE THREAD

**Issue by azhe1234** [westlake-repl/ProTrek#6]
Hello, I am a novice in biology. Can I use ProTrek for protein sequence alignment?

**Comment by LTEnjoy** [comment]
Hi!

Unlike traditional alignment tool, ProTrek finds similar proteins by embedding calculation. So it cannot give you aligned sequences. However, ProTrek is capable of retrieving proteins with similar structure and function. You could first use ProTrek to find a list of proteins and then use sequence alignment tool to align them.

**Comment by azhe1234** [comment]
> Hi!
> 
> Unlike traditional alignment tool, ProTrek finds similar proteins by embedding calculation. So it cannot give you aligned sequences. However, ProTrek is capable of retrieving proteins with similar structure and function. You could first use ProTrek to find a list of similar proteins and then use sequence alignment tool to align them for further analysis.

Okay, I understand. Thank you

**Comment by azhe1234** [comment]
> Hi!
> 
> Unlike traditional alignment tool, ProTrek finds similar proteins by embedding calculation. So it cannot give you aligned sequences. However, ProTrek is capable of retrieving proteins with similar structure and function. You could first use ProTrek to find a list of similar proteins and then use sequence alignment tool to align them for further analysis.
您好，打扰一下，我想问您一个问题，我使用ProTrek中如图所示的模态做检索，并与UniProt检索得到结果做对比，内容如下：
![image](https://github.com/user-attachments/assets/5a82e30e-a27a-447b-aff7-ad3f3aaaadb7)
在UniProt上，使用高级检索功能将功能描述转化为Field查询项，但是我发现ProTrek中检索得到的结果在UniProt检索到的结果中并未找到，是我未正确使用UniProt的高级检索还是ProTrek使用有误呢？谢谢！
![image](https://github.com/user-attachments/assets/7d718cc8-baad-4021-8ff1-db893abdaba9)

**Comment by azhe1234** [comment]
> 你好，我注意到你在UniProt的检索选项上有一个protein existence的输入，你选择的是evidence at protein level。因此UniProt会过滤掉所有低于这个等级的蛋白质。而protrek返回的结果里，比如第一个，它的存在等级是低一些的。所以这些都被UniProt过滤掉了。 ![image](https://private-user-images.githubusercontent.com/52776915/380135858-c336d127-dbdf-45c4-a5b9-2cfb89714779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjUxNjQsIm5iZiI6MTcyOTkyNDg2NCwicGF0aCI6Ii81Mjc3NjkxNS8zODAxMzU4NTgtYzMzNmQxMjctZGJkZi00NWM0LWE1YjktMmNmYjg5NzE0Nzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA2NDEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNGUxODU1MzFkYTU1MWY1NDJiNzZhOGJlNmJkY2JjMzJkNjg2NGI3ZDljMzg3NTk3NmJlN2MzZDgxMjAwNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YkGdVvA7bDUS-Yy-6GJtrUPjH7_yuliw7ofr6NCriLU)

好的我明白了，所以我想要将ProTrek的检索结果与UniProt检索的结果做对比，可以不需要设置protein existence这项吗？

**Comment by LTEnjoy** [comment]
是的，可以不需要这个设置。
