### ISSUE TITLE
是否能用ProTrek对de novo design的一群蛋白进行similarity score评分？

### ISSUE THREAD

**Issue by pillar-github** [westlake-repl/ProTrek#7]

**Comment by LTEnjoy** [comment]
如果你的蛋白质数量不多的话，可以使用我们提供的网站 http://search-protrek.com/ 来手动计算两个蛋白质之间的similarity score。如果蛋白质数量比较多的话，可以考虑以代码的形式计算蛋白质的similarity score， 具体可以参考 https://github.com/westlake-repl/ProTrek?tab=readme-ov-file#obtain-embeddings-and-calculate-similarity-score

**Comment by pillar-github** [comment]
我有大约10^5数量级的蛋白（有pdb文件和sequence），请问如何批量输入这些蛋白信息（不好意思，因为没有在介绍中看到批量输入蛋白的code），是否可以提供一下批量蛋白输入的示例数据呢？绘制图成功后，会尽快引用ProTrek文章。十分感谢如此优秀的算法文章。

**Comment by pillar-github** [comment]
好的，还有两个问题：“Obtain embeddings and calculate similarity score”节中使用的是.cif文件，是否可以用pdb文件来代替；由于这群蛋白都是从头生成的，可否把text这层信息应该怎么处理呢？
---- 回复的原邮件 ----
| 发件人 | Jin ***@***.***> |
| 发送日期 | 2024年11月21日 17:50 |
| 收件人 | westlake-repl/ProTrek ***@***.***> |
| 抄送人 | pillar-github ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [westlake-repl/ProTrek] 是够能用ProTrek对de novo design的一群蛋白进行similarity score评分？ (Issue #7) |

你好，我们在介绍中提供了如何对单条蛋白质输入计算embedding。对于多条蛋白质，只需要在外层加一个for循环即可~

**Comment by LTEnjoy** [comment]
可以用pdb文件代替cif文件的。另外，计算similarity score并不要求一定是不同的模态，例如protein-text。同模态之间也可以计算similarity score，比如你可以计算所有蛋白质序列的embedding然后用介绍中的方法计算他们的score。
